# Generated by Django 5.0.8 on 2024-08-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name_plural": "crew",
            },
        ),
        migrations.AlterField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_routes",
                to="airport.airport",
            ),
        ),
    ]
