# Generated by Django 5.0.8 on 2024-08-11 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_alter_crew_options_alter_route_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="airport.order",
            ),
            preserve_default=False,
        ),
    ]
